### PR TITLE
Escalate the severity of unused imports in analyzer

### PR DESCRIPTION
**Pull request by mehmetf**
- Also remove the prefer_mixin analysis option [This is also ignored by Flutter codebase].
- Fix unused import.

### CODE REVIEW

**Comment by mehmetf** [comment]
@luigi-rosso I notice that there's no build bot setup for this repo. How do you locally develop this package? Would my analysis options change catch these kinds of errors before you upload the package to pub?

**Comment by luigi-rosso** [comment]
Thanks for the PR!

We currently deploy manually. I never looked into writing a script for it as I currently manually merge to stable, change versions, write the changelog, and then "pub publish" when that's all ready. What do you recommend we use?

**Comment by mehmetf** [comment]
You are in "fast prototyping" mode so it is expected to build up some code debt at this stage. Eventually, you would need a CI setup and tests to make sure the functionality does not break.

For now, I would like to know what local commands you use when you are testing these packages. When you make a change, do you use `flutter` command to deploy some sample app somewhere and test it out? How do you develop?

For instance when I run `flutter analyze` under flare_dart, it finds 672 issues (missing return types etc). I don't think all of them are legit which is why most people customize their analysis_options file.

**Comment by luigi-rosso** [comment]
Prior to publishing we ```flutter run``` all of the examples in the [example](https://github.com/2d-inc/Flare-Flutter/tree/stable/example) folder and make sure they look and behave properly. I do that in the master branch and then update the changelogs. I then merge it to dev and then stable (if it's a feature that is compatible with Flutter stable) and then do a final test (usually just make sure the simple example runs once fully merged) and publish to pub.

Develop in VSCode but I almost always deploy via the terminal with ```flutter run```.

What do most other packages do as far as branch strategy and CD for pub? We can definitely add CI with some tests, pub CD seems to raise a lot of questions (like who does the version changing?).

Our branching strategy evolved when there were breaking changes between master and stable which required us to develop our features in master but maintain an older branch with cherrypicked changes compatible with stable for pub. The dev branch is meant to be identical to master but used via git reference in pub instead of local path like master.

**Comment by mehmetf** [comment]
Unfortunately, `flutter run` does not do any analysis checks.

Hopefully with my change, you will see these as errors in VSCode.

**Pull request merged**
